project:
  type: website

website:
  title: "Ouyang Qimeng | Bioinformatics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: notes.qmd
        text: Bioinfo Notes
      - href: protocols.qmd
        text: Protocols
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
